name: Auto Image Rebuild
on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Login to DockerHub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Regular Docker Image
        uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935 # v2.6.1
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: technoguyfication/caddy-cloudflare:latest

  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Login to DockerHub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Alpine Docker Image
        uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935 # v2.6.1
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: technoguyfication/caddy-cloudflare:alpine
          file: "Dockerfile.alpine"
